### ISSUE TITLE
Set up wiki

### ISSUE THREAD

**Issue by skddc** [remotestorage/remotestorage.io#78]

**Comment by michielbdejong** [comment]
wiki? I thought we were [working on a new site](https://community.remotestorage.io/t/website-relaunch-concept-content-brainstorming-collecting/234)?

**Comment by skddc** [comment]
Both. Unfortunately it's been impossible within the last half year to set up a call with the person who wants to work on it.

Don't think of this a replacement or as anything we need to discuss. A few of us will be trying this out on the side without having it linked and we'll propose how and when to integrate it if or when it makes sense.

**Comment by michielbdejong** [comment]
I am against this. It sounds like a [xkcd-972](http://www.explainxkcd.com/wiki/index.php/927:_Standards)-style reaction to our already scattered developer documentation.
Right now our documentation for developers is in already in many, many place:

* ['integrate' tutorials on the live site](https://remotestorage.io/integrate/)
* [new site that was never (yet) launched](https://rerelaunch.5apps.com/)
* [forum](https://community.remotestorage.io/)
* [doc folder in the repo](https://github.com/remotestorage/remotestorage.js/tree/master/doc)
* [naturaldocs pages](https://remotestorage.io/doc/code/files/remotestorage-js.html)
* [github readme](https://github.com/remotestorage/remotestorage.js#remotestoragejs)

And then I'm not even counting the spec itself yet. ;)
Let's not add yet another, because it will lead to people adding things on the wiki which could easily be in the naturaldocs or in the tutorials or on the forum.

**Comment by skddc** [comment]
You can be against whatever you want. That won't stop some of us experimenting with it. As I said, we won't link it anywhere without a proposal/pull request. You can discuss it then.

**Comment by michielbdejong** [comment]
OK, I guess "who builds, decides", so if you are working on docs, then you can also decide where you write them. Just two pieces of advice, and then I'll shut up:

* Make it public. This is an open source project. If a wiki exists but it's not linked to, then it sounds like this new group of new "core" people are not open to collaborating with "non core" people, and will create a psychological threshold, and ultimately, you will have made it a closed project where decisions are taken behind closed doors. That would be a shame.
* Consolidate (once it goes live) some of the existing docs locations into your new wiki, especially for instance the doc folder in the repo, and probably also some of the pinned posts from the forum, can probably be moved into it. It will make everything easier to find!

HTH, good luck with it

**Comment by skddc** [comment]
> Make it public.
 
That's the idea. As I wrote:

> Everyone can follow our experiment on both IRC and the wiki itself, as soon as it's set up.

.
 
> Consolidate (once it goes live) some of the existing docs

Part of the experiment is finding out if that makes sense and what to move there or not move there.

**Comment by skddc** [comment]
The wiki has been set up and you are all invited to add and/or edit anything:

https://wiki.remotestorage.io

The Notes page is a great place to just drop any notes and links related to RS you stumble upon, by the way.
